# 使用的语言
language: cn
# 是否开启调试模式: 对原配置文件与语言文件进行覆盖
debug: true
# 存储方式: 文件、sqlite、mysql
storage:
  type: sqlite
  #  TODO mysql数据库链接配置
  mysql:
    host: localhost
    port: 3306
    database: jebe_market
    username: root
    password: ""
    table_prefix: jebe_
    connection_pool: 10

settings:
  shop:
    min_name_length: 2
    max_name_length: 16

interaction:
  # 输入超时时间（秒）
  input_timeout: 30
  # 是否允许颜色代码
  allow_color_code: true

# 摆摊模式（TODO ）
stall_mode:
  # 是否启用摆摊模式
  enabled: true
  # 摆摊时的费用（每次摆摊需要支付的金额）
  cost: 50

# 禁止使用的商品名称关键词
filter:
  banned_words: # 违禁词列表
    - "admin"
    - "op"
    - "staff"

#  区域限制(TODO)
restrictions:
  # 禁止创建商铺的世界列表
  banned_worlds: [ world_pvp ]
  # 每个区块最大商铺数
  chunk_max_shops: 5

# 创建商铺需要多少余额
shop_create_cost: 100
# 创建商铺上限
shop_create_limit: 10

# 续费商铺每日费用(TODO)
shop_rent_daily: 10

# 商铺内商品上限
shop_item_limit: 20
# 商品上架费用
item_list_cost: 5

# 转交商铺权限需要多少余额
shop_transfer_cost: 100

# 商铺修改name需要多少余额
shop_rename_cost: 50
# 商铺修改介绍需要多少余额
shop_desc_cost: 50
# 商品单价最大为多少
max_price: 99999999999

# 税收
tax:
  #  购买
  buy: 0
  #  出售
  sell: 0
