# 使用的语言
language: cn
# 是否开启调试模式: 对原配置文件与语言文件进行覆盖
debug: true
# 存储方式: 文件、sqlite、mysql
storage:
  type: sqlite
  #  TODO mysql数据库链接配置
  mysql:
    host: localhost
    port: 3306
    database: jebe_market
    username: root
    password: ""
    table_prefix: jebe_
    connection_pool: 10

settings:
  shop:
    create:
      #        创建商铺需要多少余额
      cost: 1000.00
      #          创建商铺名称长度限制
      min_name_length: 2
      #          创建商铺名称长度限制
      max_name_length: 16
      #          创建商铺数量限制
      create_limit: 6
      #          创建商铺名称过滤
      filter:
        banned_words: # 违禁词列表
          - "admin"
          - "op"
          - "staff"
    #          修改商铺名称长度限制
    edit:
      name:
        #          修改商铺名称长度限制
        min_length: 2
        #          修改商铺名称长度限制
        max_length: 16
        #            修改商铺名称需要花费
        cost: 500
      lore:
        #          修改商铺介绍长度限制
        max_length: 256

      owner:
        #          修改商铺拥有者需要花费
        cost: 20
  item:
    #        商品最大价格
    max_price: 1000000
    up:
      #        商品上架需要花费
      cost: 100.00

# 交互相关
interaction:
  # 输入超时时间（秒）
  input_timeout: 30

# 摆摊模式（TODO ）
stall_mode:
  # 是否启用摆摊模式
  enabled: true
  # 摆摊时的费用（每次摆摊需要支付的金额）
  cost: 50

#  区域限制(TODO)
restrictions:
  # 禁止创建商铺的世界列表
  banned_worlds: [ world_pvp ]
  # 每个区块最大商铺数
  chunk_max_shops: 5
# 续费商铺每日费用(TODO)
shop_rent_daily: 10

# 税收
tax:
  #  购买
  buy: 0.5
  #  出售
  sell: 0.5
